ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code VARCHAR(100) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_id INT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE orders ADD CONSTRAINT fk_orders_coupon_id FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE SET NULL;
